# Basic
title: Aunger
subtitle: 个人站
description: 欢迎来到我的个人博客
# 头像里面的标题
avatarTitle: Aunger
# 头像里面的描述
avatarDesc: Test / UID
url: "https://10000101.xyz"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # livere: MTAyMC81NzQ1Mi8zMzkxNg==
    # disqus: Aunger
    # uyan: 2143225  # 有言id,登录有言官网申请，有广告关了

# Social
social:
    weibo: Aunger 
    github: aunger01
    # zhihu: aunger01
    # juejin: aunger
    jianshu: d36aca9e76eb
    # twitter: 
    mail: vip@L1N2.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
   id: fde0ae1ed9908cb0c10f5a6e565315cd  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#   id: 输入Google analytics ID 
#   host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://aunger.eu.org
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 动态, description: moments, url: '/moments'}
    - {title: 关于我, description: about, url: '/about'}


plugins: [jekyll-sitemap]


